import Testing
@testable import OmniContainer

@Suite("Blink Guest Networking")
struct BlinkGuestNetworkingTests {
    @Test("Resolver config drops unusable Apple IPv6 nameservers")
    func filtersAppleIpv6Resolvers() {
        let hostResolv = """
        # generated by host
        nameserver 2001:558:feed::1
        nameserver 75.75.75.75
        nameserver 75.75.76.76
        search example.internal
        """

        let guestResolv = BlinkGuestNetworking.resolvConf(hostContents: hostResolv)

#if os(macOS) || os(iOS) || os(tvOS) || os(watchOS) || os(visionOS)
        #expect(!guestResolv.localizedStandardContains("2001:558:feed::1"))
        #expect(guestResolv.localizedStandardContains("nameserver 75.75.75.75"))
        #expect(guestResolv.localizedStandardContains("nameserver 75.75.76.76"))
#else
        #expect(guestResolv.localizedStandardContains("nameserver 2001:558:feed::1"))
#endif
        #expect(guestResolv.localizedStandardContains("search example.internal"))
    }

    @Test("Resolver config falls back to public IPv4 resolvers when none survive filtering")
    func fallsBackToPublicIpv4Resolvers() {
        let hostResolv = """
        nameserver 2001:558:feed::1
        nameserver 2606:4700::1111
        """

        let guestResolv = BlinkGuestNetworking.resolvConf(hostContents: hostResolv)

        #expect(guestResolv.localizedStandardContains("nameserver 8.8.8.8"))
        #expect(guestResolv.localizedStandardContains("nameserver 8.8.4.4"))
    }
}
