public enum KnownModels {
    // Ordered by preference within provider (newest/best first).
    public static let all: [ModelInfo] = [
        // Anthropic
        ModelInfo(
            id: "claude-opus-4-6[1m]",
            provider: "anthropic",
            displayName: "Claude Opus 4.6 (1M)",
            contextWindow: 1_000_000,
            maxOutput: 128_000,
            supportsTools: true,
            supportsVision: true,
            supportsReasoning: true,
            inputCostPerMillion: 5,
            outputCostPerMillion: 25,
            aliases: ["opus-1m", "claude-opus-1m"]
        ),
        ModelInfo(
            id: "claude-opus-4-6",
            provider: "anthropic",
            displayName: "Claude Opus 4.6",
            contextWindow: 200_000,
            maxOutput: 128_000,
            supportsTools: true,
            supportsVision: true,
            supportsReasoning: true,
            inputCostPerMillion: 5,
            outputCostPerMillion: 25,
            aliases: ["opus", "claude-opus", "latest-anthropic"]
        ),
        ModelInfo(
            id: "claude-sonnet-4-6[1m]",
            provider: "anthropic",
            displayName: "Claude Sonnet 4.6 (1M)",
            contextWindow: 1_000_000,
            maxOutput: 64_000,
            supportsTools: true,
            supportsVision: true,
            supportsReasoning: true,
            inputCostPerMillion: 3,
            outputCostPerMillion: 15,
            aliases: ["sonnet-1m", "claude-sonnet-1m"]
        ),
        ModelInfo(
            id: "claude-sonnet-4-6",
            provider: "anthropic",
            displayName: "Claude Sonnet 4.6",
            contextWindow: 200_000,
            maxOutput: 64_000,
            supportsTools: true,
            supportsVision: true,
            supportsReasoning: true,
            inputCostPerMillion: 3,
            outputCostPerMillion: 15,
            aliases: ["sonnet", "claude-sonnet"]
        ),
        ModelInfo(
            id: "claude-haiku-4-5",
            provider: "anthropic",
            displayName: "Claude Haiku 4.5",
            contextWindow: 200_000,
            maxOutput: 64_000,
            supportsTools: true,
            supportsVision: true,
            supportsReasoning: true,
            inputCostPerMillion: 1,
            outputCostPerMillion: 5,
            aliases: ["haiku", "claude-haiku"]
        ),

        // OpenAI
        ModelInfo(
            id: "gpt-5.4",
            provider: "openai",
            displayName: "GPT-5.4",
            contextWindow: 400_000,
            maxOutput: 128_000,
            supportsTools: true,
            supportsVision: true,
            supportsReasoning: true,
            inputCostPerMillion: 35,
            outputCostPerMillion: 140,
            aliases: ["gpt5", "gpt-5", "latest-openai"]
        ),
        ModelInfo(
            id: "gpt-5.4-pro",
            provider: "openai",
            displayName: "GPT-5.4 Pro",
            contextWindow: 400_000,
            maxOutput: 128_000,
            supportsTools: true,
            supportsVision: true,
            supportsReasoning: true,
            inputCostPerMillion: 70,
            outputCostPerMillion: 280,
            aliases: ["gpt5-pro", "gpt-5-pro", "latest-openai-pro"]
        ),
        ModelInfo(
            id: "gpt-5.3-codex",
            provider: "openai",
            displayName: "GPT-5.3 Codex",
            contextWindow: 400_000,
            maxOutput: 128_000,
            supportsTools: true,
            supportsVision: true,
            supportsReasoning: true,
            inputCostPerMillion: 3,
            outputCostPerMillion: 12,
            aliases: ["codex", "gpt-5-codex", "latest-openai-codex"]
        ),
        ModelInfo(
            id: "gpt-5.3-codex-spark",
            provider: "openai",
            displayName: "GPT-5.3 Codex Spark",
            contextWindow: 400_000,
            maxOutput: 128_000,
            supportsTools: true,
            supportsVision: true,
            supportsReasoning: true,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["codex-spark", "gpt-5.3-codex-spark", "gpt53-codex-spark", "latest-openai-codex-spark"]
        ),
        ModelInfo(
            id: "gpt-5.2",
            provider: "openai",
            displayName: "GPT-5.2",
            contextWindow: 400_000,
            maxOutput: 128_000,
            supportsTools: true,
            supportsVision: true,
            supportsReasoning: true,
            inputCostPerMillion: 15,
            outputCostPerMillion: 60,
            aliases: ["gpt-5.2"]
        ),
        ModelInfo(
            id: "gpt-5.2-codex",
            provider: "openai",
            displayName: "GPT-5.2 Codex",
            contextWindow: 400_000,
            maxOutput: 128_000,
            supportsTools: true,
            supportsVision: true,
            supportsReasoning: true,
            inputCostPerMillion: 2,
            outputCostPerMillion: 8,
            aliases: ["gpt-5.2-codex"]
        ),
        ModelInfo(
            id: "gpt-5.1",
            provider: "openai",
            displayName: "GPT-5.1",
            contextWindow: 400_000,
            maxOutput: 128_000,
            supportsTools: true,
            supportsVision: true,
            supportsReasoning: true,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["gpt-5.1"]
        ),
        ModelInfo(
            id: "gpt-5.1-codex-max",
            provider: "openai",
            displayName: "GPT-5.1 Codex Max",
            contextWindow: 400_000,
            maxOutput: 128_000,
            supportsTools: true,
            supportsVision: true,
            supportsReasoning: true,
            inputCostPerMillion: 6,
            outputCostPerMillion: 24,
            aliases: ["codex-max", "gpt-5.1-codex-max"]
        ),
        ModelInfo(
            id: "gpt-5.1-codex",
            provider: "openai",
            displayName: "GPT-5.1 Codex",
            contextWindow: 400_000,
            maxOutput: 128_000,
            supportsTools: true,
            supportsVision: true,
            supportsReasoning: true,
            inputCostPerMillion: 1.5,
            outputCostPerMillion: 6,
            aliases: ["gpt-5.1-codex"]
        ),
        ModelInfo(
            id: "gpt-5-mini",
            provider: "openai",
            displayName: "GPT-5 Mini",
            contextWindow: 400_000,
            maxOutput: 128_000,
            supportsTools: true,
            supportsVision: true,
            supportsReasoning: true,
            inputCostPerMillion: 0.25,
            outputCostPerMillion: 2,
            aliases: ["gpt-5-mini"]
        ),
        ModelInfo(
            id: "gpt-5-nano",
            provider: "openai",
            displayName: "GPT-5 Nano",
            contextWindow: 400_000,
            maxOutput: 128_000,
            supportsTools: true,
            supportsVision: true,
            supportsReasoning: true,
            inputCostPerMillion: 0.05,
            outputCostPerMillion: 0.4,
            aliases: ["gpt-5-nano"]
        ),
        ModelInfo(
            id: "gpt-4.1",
            provider: "openai",
            displayName: "GPT-4.1",
            contextWindow: 1_000_000,
            maxOutput: 32_768,
            supportsTools: true,
            supportsVision: true,
            supportsReasoning: false,
            inputCostPerMillion: 2,
            outputCostPerMillion: 8,
            aliases: ["gpt-4.1"]
        ),

        // Gemini
        ModelInfo(
            id: "gemini-3.1-pro-preview",
            provider: "gemini",
            displayName: "Gemini 3.1 Pro Preview",
            contextWindow: 1_048_576,
            maxOutput: 65_536,
            supportsTools: true,
            supportsVision: true,
            supportsReasoning: true,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["gemini-3.1-pro", "gemini-pro", "latest-gemini", "latest-gemini-pro"]
        ),
        ModelInfo(
            id: "gemini-3.1-pro-preview-customtools",
            provider: "gemini",
            displayName: "Gemini 3.1 Pro Preview Custom Tools",
            contextWindow: 1_048_576,
            maxOutput: 65_536,
            supportsTools: true,
            supportsVision: true,
            supportsReasoning: true,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["gemini-3.1-pro-customtools", "gemini-pro-customtools"]
        ),
        ModelInfo(
            id: "gemini-3-flash-preview",
            provider: "gemini",
            displayName: "Gemini 3 Flash Preview",
            contextWindow: 1_048_576,
            maxOutput: 65_536,
            supportsTools: true,
            supportsVision: true,
            supportsReasoning: true,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["gemini-3-flash", "latest-gemini-flash"]
        ),
        ModelInfo(
            id: "gemini-3.1-flash-lite-preview",
            provider: "gemini",
            displayName: "Gemini 3.1 Flash-Lite Preview",
            contextWindow: 1_048_576,
            maxOutput: 65_536,
            supportsTools: true,
            supportsVision: true,
            supportsReasoning: true,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["gemini-3.1-flash-lite", "gemini-flash-lite"]
        ),
        ModelInfo(
            id: "gemini-2.5-pro",
            provider: "gemini",
            displayName: "Gemini 2.5 Pro",
            contextWindow: 1_048_576,
            maxOutput: 65_536,
            supportsTools: true,
            supportsVision: true,
            supportsReasoning: true,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["gemini-2.5-pro"]
        ),
        ModelInfo(
            id: "gemini-2.5-flash",
            provider: "gemini",
            displayName: "Gemini 2.5 Flash",
            contextWindow: 1_048_576,
            maxOutput: 65_536,
            supportsTools: true,
            supportsVision: true,
            supportsReasoning: true,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["gemini-2.5-flash"]
        ),
        ModelInfo(
            id: "gemini-2.5-flash-lite",
            provider: "gemini",
            displayName: "Gemini 2.5 Flash-Lite",
            contextWindow: 1_048_576,
            maxOutput: 65_536,
            supportsTools: true,
            supportsVision: true,
            supportsReasoning: true,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["gemini-2.5-flash-lite"]
        ),

        // Cerebras
        ModelInfo(
            id: "zai-glm-4.7",
            provider: "cerebras",
            displayName: "Z.AI GLM 4.7",
            contextWindow: 131_072,
            maxOutput: 65_536,
            supportsTools: true,
            supportsVision: false,
            supportsReasoning: true,
            inputCostPerMillion: 0.6,
            outputCostPerMillion: 0.8,
            aliases: ["glm-4.7", "latest-cerebras"]
        ),
        ModelInfo(
            id: "qwen-3-235b-a22b-thinking-2507",
            provider: "cerebras",
            displayName: "Qwen 3 235B A22B Thinking 2507",
            contextWindow: 131_072,
            maxOutput: 65_536,
            supportsTools: true,
            supportsVision: false,
            supportsReasoning: true,
            inputCostPerMillion: 0.6,
            outputCostPerMillion: 0.8,
            aliases: ["qwen-3-thinking", "qwen-235b-thinking"]
        ),
        ModelInfo(
            id: "qwen-3-235b-a22b-instruct-2507",
            provider: "cerebras",
            displayName: "Qwen 3 235B A22B Instruct 2507",
            contextWindow: 131_072,
            maxOutput: 65_536,
            supportsTools: true,
            supportsVision: false,
            supportsReasoning: false,
            inputCostPerMillion: 0.4,
            outputCostPerMillion: 0.8,
            aliases: ["qwen-3-235b", "qwen-235b"]
        ),
        ModelInfo(
            id: "openai/gpt-oss-120b",
            provider: "cerebras",
            displayName: "GPT-OSS 120B",
            contextWindow: 131_072,
            maxOutput: 131_072,
            supportsTools: true,
            supportsVision: false,
            supportsReasoning: true,
            inputCostPerMillion: 0.6,
            outputCostPerMillion: 0.6,
            aliases: ["gpt-oss", "gpt-oss-120b", "oss-120b"]
        ),
        ModelInfo(
            id: "llama3.1-8b",
            provider: "cerebras",
            displayName: "Llama 3.1 8B",
            contextWindow: 32_768,
            maxOutput: 8_192,
            supportsTools: true,
            supportsVision: false,
            supportsReasoning: false,
            inputCostPerMillion: 0.1,
            outputCostPerMillion: 0.1,
            aliases: ["llama-3.1", "llama-8b"]
        ),

        // Groq
        ModelInfo(
            id: "openai/gpt-oss-120b",
            provider: "groq",
            displayName: "GPT-OSS 120B",
            contextWindow: 131_072,
            maxOutput: 65_536,
            supportsTools: true,
            supportsVision: false,
            supportsReasoning: true,
            inputCostPerMillion: 0.15,
            outputCostPerMillion: 0.6,
            aliases: ["groq-gpt-oss-120b", "latest-groq"]
        ),
        ModelInfo(
            id: "meta-llama/llama-4-maverick-17b-128e-instruct",
            provider: "groq",
            displayName: "Llama 4 Maverick 17B 128E Instruct",
            contextWindow: 131_072,
            maxOutput: 8_192,
            supportsTools: true,
            supportsVision: true,
            supportsReasoning: false,
            inputCostPerMillion: 0.2,
            outputCostPerMillion: 0.6,
            aliases: ["llama-4-maverick", "groq-llama-4-maverick"]
        ),
        ModelInfo(
            id: "moonshotai/kimi-k2-instruct-0905",
            provider: "groq",
            displayName: "Kimi K2 Instruct 0905",
            contextWindow: 262_144,
            maxOutput: 16_384,
            supportsTools: true,
            supportsVision: false,
            supportsReasoning: false,
            inputCostPerMillion: 1,
            outputCostPerMillion: 3,
            aliases: ["kimi-k2", "kimi-k2-0905", "groq-kimi-k2", "groq-kimi-k2-0905"]
        ),
        ModelInfo(
            id: "qwen/qwen3-32b",
            provider: "groq",
            displayName: "Qwen3 32B",
            contextWindow: 131_072,
            maxOutput: 40_960,
            supportsTools: true,
            supportsVision: false,
            supportsReasoning: true,
            inputCostPerMillion: 0.29,
            outputCostPerMillion: 0.59,
            aliases: ["qwen3-32b", "groq-qwen3-32b"]
        ),
        ModelInfo(
            id: "openai/gpt-oss-20b",
            provider: "groq",
            displayName: "GPT-OSS 20B",
            contextWindow: 131_072,
            maxOutput: 65_536,
            supportsTools: true,
            supportsVision: false,
            supportsReasoning: true,
            inputCostPerMillion: 0.075,
            outputCostPerMillion: 0.3,
            aliases: ["gpt-oss-20b", "groq-gpt-oss-20b"]
        ),
        ModelInfo(
            id: "meta-llama/llama-4-scout-17b-16e-instruct",
            provider: "groq",
            displayName: "Llama 4 Scout 17B 16E Instruct",
            contextWindow: 131_072,
            maxOutput: 8_192,
            supportsTools: true,
            supportsVision: true,
            supportsReasoning: false,
            inputCostPerMillion: 0.11,
            outputCostPerMillion: 0.34,
            aliases: ["llama-4-scout", "groq-llama-4-scout"]
        ),
        ModelInfo(
            id: "llama-3.3-70b-versatile",
            provider: "groq",
            displayName: "Llama 3.3 70B Versatile",
            contextWindow: 131_072,
            maxOutput: 32_768,
            supportsTools: true,
            supportsVision: false,
            supportsReasoning: false,
            inputCostPerMillion: 0.59,
            outputCostPerMillion: 0.79,
            aliases: ["llama-3.3", "groq-llama-3.3"]
        ),
        ModelInfo(
            id: "groq/compound",
            provider: "groq",
            displayName: "Groq Compound",
            contextWindow: 131_072,
            maxOutput: 8_192,
            supportsTools: true,
            supportsVision: false,
            supportsReasoning: false,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["compound", "groq-compound"]
        ),
        ModelInfo(
            id: "groq/compound-mini",
            provider: "groq",
            displayName: "Groq Compound Mini",
            contextWindow: 131_072,
            maxOutput: 8_192,
            supportsTools: true,
            supportsVision: false,
            supportsReasoning: false,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["compound-mini", "groq-compound-mini"]
        ),
        ModelInfo(
            id: "llama-3.1-8b-instant",
            provider: "groq",
            displayName: "Llama 3.1 8B Instant",
            contextWindow: 131_072,
            maxOutput: 131_072,
            supportsTools: true,
            supportsVision: false,
            supportsReasoning: false,
            inputCostPerMillion: 0.05,
            outputCostPerMillion: 0.08,
            aliases: ["llama-3.1-8b", "groq-llama-3.1-8b"]
        ),
        ModelInfo(
            id: "allam-2-7b",
            provider: "groq",
            displayName: "Allam 2 7B",
            contextWindow: 4_096,
            maxOutput: 4_096,
            supportsTools: true,
            supportsVision: false,
            supportsReasoning: false,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["allam", "allam-7b"]
        ),
        ModelInfo(
            id: "openai/gpt-oss-safeguard-20b",
            provider: "groq",
            displayName: "GPT-OSS Safeguard 20B",
            contextWindow: 131_072,
            maxOutput: 65_536,
            supportsTools: false,
            supportsVision: false,
            supportsReasoning: false,
            inputCostPerMillion: 0.075,
            outputCostPerMillion: 0.3,
            aliases: ["gpt-oss-safeguard", "groq-gpt-oss-safeguard"]
        ),
        ModelInfo(
            id: "meta-llama/llama-guard-4-12b",
            provider: "groq",
            displayName: "Llama Guard 4 12B",
            contextWindow: 131_072,
            maxOutput: 1_024,
            supportsTools: false,
            supportsVision: false,
            supportsReasoning: false,
            inputCostPerMillion: 0.2,
            outputCostPerMillion: 0.2,
            aliases: ["llama-guard-4", "groq-llama-guard"]
        ),
        ModelInfo(
            id: "meta-llama/llama-prompt-guard-2-86m",
            provider: "groq",
            displayName: "Llama Prompt Guard 2 86M",
            contextWindow: 512,
            maxOutput: 512,
            supportsTools: false,
            supportsVision: false,
            supportsReasoning: false,
            inputCostPerMillion: 0.04,
            outputCostPerMillion: 0.04,
            aliases: ["prompt-guard-86m", "groq-prompt-guard-86m"]
        ),
        ModelInfo(
            id: "meta-llama/llama-prompt-guard-2-22m",
            provider: "groq",
            displayName: "Llama Prompt Guard 2 22M",
            contextWindow: 512,
            maxOutput: 512,
            supportsTools: false,
            supportsVision: false,
            supportsReasoning: false,
            inputCostPerMillion: 0.03,
            outputCostPerMillion: 0.03,
            aliases: ["prompt-guard-22m", "groq-prompt-guard-22m"]
        ),
        ModelInfo(
            id: "whisper-large-v3",
            provider: "groq",
            displayName: "Whisper Large V3",
            contextWindow: 448,
            maxOutput: 448,
            supportsTools: false,
            supportsVision: false,
            supportsReasoning: false,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["whisper-v3", "groq-whisper-v3"]
        ),
        ModelInfo(
            id: "whisper-large-v3-turbo",
            provider: "groq",
            displayName: "Whisper Large V3 Turbo",
            contextWindow: 448,
            maxOutput: 448,
            supportsTools: false,
            supportsVision: false,
            supportsReasoning: false,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["whisper-v3-turbo", "groq-whisper-v3-turbo"]
        ),
        ModelInfo(
            id: "canopylabs/orpheus-v1-english",
            provider: "groq",
            displayName: "Orpheus V1 English",
            contextWindow: 4_000,
            maxOutput: 50_000,
            supportsTools: false,
            supportsVision: false,
            supportsReasoning: false,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["orpheus-english", "groq-orpheus-english"]
        ),
        ModelInfo(
            id: "canopylabs/orpheus-arabic-saudi",
            provider: "groq",
            displayName: "Orpheus Arabic Saudi",
            contextWindow: 4_000,
            maxOutput: 50_000,
            supportsTools: false,
            supportsVision: false,
            supportsReasoning: false,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["orpheus-arabic", "groq-orpheus-arabic"]
        ),
    ]
}
