public enum KnownModels {
    // Ordered by preference within provider (newest/best first).
    public static let all: [ModelInfo] = [
        // Anthropic
        ModelInfo(
            id: "claude-opus-4-6[1m]",
            provider: "anthropic",
            displayName: "Claude Opus 4.6 (1M)",
            contextWindow: 1_000_000,
            maxOutput: nil,
            supportsTools: true,
            supportsVision: true,
            supportsReasoning: true,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["opus-1m", "claude-opus-1m"]
        ),
        ModelInfo(
            id: "claude-opus-4-6",
            provider: "anthropic",
            displayName: "Claude Opus 4.6",
            contextWindow: 200_000,
            maxOutput: nil,
            supportsTools: true,
            supportsVision: true,
            supportsReasoning: true,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["opus", "claude-opus"]
        ),
        ModelInfo(
            id: "claude-sonnet-4-6[1m]",
            provider: "anthropic",
            displayName: "Claude Sonnet 4.6 (1M)",
            contextWindow: 1_000_000,
            maxOutput: nil,
            supportsTools: true,
            supportsVision: true,
            supportsReasoning: true,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["sonnet-1m", "claude-sonnet-1m"]
        ),
        ModelInfo(
            id: "claude-sonnet-4-6",
            provider: "anthropic",
            displayName: "Claude Sonnet 4.6",
            contextWindow: 200_000,
            maxOutput: nil,
            supportsTools: true,
            supportsVision: true,
            supportsReasoning: true,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["sonnet", "claude-sonnet"]
        ),
        ModelInfo(
            id: "claude-haiku-4-5",
            provider: "anthropic",
            displayName: "Claude Haiku 4.5",
            contextWindow: 200_000,
            maxOutput: nil,
            supportsTools: true,
            supportsVision: true,
            supportsReasoning: true,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["haiku", "claude-haiku"]
        ),

        // OpenAI
        ModelInfo(
            id: "gpt-5.2",
            provider: "openai",
            displayName: "GPT-5.2",
            contextWindow: 1_047_576,
            maxOutput: nil,
            supportsTools: true,
            supportsVision: true,
            supportsReasoning: true,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["gpt5", "gpt-5", "latest-openai"]
        ),
        ModelInfo(
            id: "gpt-5.2-mini",
            provider: "openai",
            displayName: "GPT-5.2 Mini",
            contextWindow: 1_047_576,
            maxOutput: nil,
            supportsTools: true,
            supportsVision: true,
            supportsReasoning: true,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["gpt-5-mini"]
        ),
        ModelInfo(
            id: "gpt-5.2-codex",
            provider: "openai",
            displayName: "GPT-5.2 Codex",
            contextWindow: 1_047_576,
            maxOutput: nil,
            supportsTools: true,
            supportsVision: true,
            supportsReasoning: true,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["codex", "gpt-5-codex"]
        ),

        // Gemini
        ModelInfo(
            id: "gemini-3-pro-preview",
            provider: "gemini",
            displayName: "Gemini 3 Pro (Preview)",
            contextWindow: 1_048_576,
            maxOutput: nil,
            supportsTools: true,
            supportsVision: true,
            supportsReasoning: true,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["gemini-3-pro", "latest-gemini-pro"]
        ),
        ModelInfo(
            id: "gemini-3-flash-preview",
            provider: "gemini",
            displayName: "Gemini 3 Flash (Preview)",
            contextWindow: 1_048_576,
            maxOutput: nil,
            supportsTools: true,
            supportsVision: true,
            supportsReasoning: true,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["gemini-3-flash", "latest-gemini"]
        ),

        // Cerebras
        ModelInfo(
            id: "zai-glm-4.7",
            provider: "cerebras",
            displayName: "Z.AI GLM 4.7 (Preview)",
            contextWindow: 131_072,
            maxOutput: nil,
            supportsTools: true,
            supportsVision: true,
            supportsReasoning: true,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["glm-4.7", "latest-cerebras"]
        ),
        ModelInfo(
            id: "qwen-3-235b-a22b-instruct-2507",
            provider: "cerebras",
            displayName: "Qwen 3 235B A22B Instruct 2507",
            contextWindow: 131_072,
            maxOutput: nil,
            supportsTools: true,
            supportsVision: true,
            supportsReasoning: true,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["qwen-3-235b"]
        ),
        ModelInfo(
            id: "gpt-oss-120b",
            provider: "cerebras",
            displayName: "GPT-OSS 120B",
            contextWindow: 131_072,
            maxOutput: nil,
            supportsTools: true,
            supportsVision: true,
            supportsReasoning: true,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["gpt-oss", "oss-120b"]
        ),
        ModelInfo(
            id: "qwen-3-32b",
            provider: "cerebras",
            displayName: "Qwen 3 32B",
            contextWindow: 131_072,
            maxOutput: nil,
            supportsTools: true,
            supportsVision: true,
            supportsReasoning: true,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["qwen-3", "qwen-32b"]
        ),
        ModelInfo(
            id: "llama-3.3-70b",
            provider: "cerebras",
            displayName: "Llama 3.3 70B",
            contextWindow: 131_072,
            maxOutput: nil,
            supportsTools: true,
            supportsVision: true,
            supportsReasoning: true,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["llama-3.3", "llama-70b"]
        ),
        ModelInfo(
            id: "llama3.1-8b",
            provider: "cerebras",
            displayName: "Llama 3.1 8B",
            contextWindow: 131_072,
            maxOutput: nil,
            supportsTools: true,
            supportsVision: true,
            supportsReasoning: true,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["llama-3.1", "llama-8b"]
        ),

        // Groq (live /openai/v1/models as of 2026-02-15)
        ModelInfo(
            id: "openai/gpt-oss-120b",
            provider: "groq",
            displayName: "GPT-OSS 120B",
            contextWindow: 131_072,
            maxOutput: 65_536,
            supportsTools: true,
            supportsVision: false,
            supportsReasoning: true,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["gpt-oss-120b", "groq-gpt-oss-120b", "latest-groq"]
        ),
        ModelInfo(
            id: "qwen/qwen3-32b",
            provider: "groq",
            displayName: "Qwen3 32B",
            contextWindow: 131_072,
            maxOutput: 40_960,
            supportsTools: true,
            supportsVision: false,
            supportsReasoning: true,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["qwen3-32b", "groq-qwen3-32b"]
        ),
        ModelInfo(
            id: "meta-llama/llama-4-maverick-17b-128e-instruct",
            provider: "groq",
            displayName: "Llama 4 Maverick 17B 128E Instruct",
            contextWindow: 131_072,
            maxOutput: 8_192,
            supportsTools: true,
            supportsVision: true,
            supportsReasoning: false,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["llama-4-maverick", "groq-llama-4-maverick"]
        ),
        ModelInfo(
            id: "moonshotai/kimi-k2-instruct-0905",
            provider: "groq",
            displayName: "Kimi K2 Instruct 0905",
            contextWindow: 262_144,
            maxOutput: 16_384,
            supportsTools: true,
            supportsVision: false,
            supportsReasoning: false,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["kimi-k2-0905", "groq-kimi-k2-0905"]
        ),
        ModelInfo(
            id: "llama-3.3-70b-versatile",
            provider: "groq",
            displayName: "Llama 3.3 70B Versatile",
            contextWindow: 131_072,
            maxOutput: 32_768,
            supportsTools: true,
            supportsVision: false,
            supportsReasoning: false,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["llama-3.3-70b", "groq-llama-3.3-70b"]
        ),
        ModelInfo(
            id: "groq/compound",
            provider: "groq",
            displayName: "Groq Compound",
            contextWindow: 131_072,
            maxOutput: 8_192,
            supportsTools: true,
            supportsVision: false,
            supportsReasoning: false,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["compound", "groq-compound"]
        ),
        ModelInfo(
            id: "openai/gpt-oss-20b",
            provider: "groq",
            displayName: "GPT-OSS 20B",
            contextWindow: 131_072,
            maxOutput: 65_536,
            supportsTools: true,
            supportsVision: false,
            supportsReasoning: true,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["gpt-oss-20b", "groq-gpt-oss-20b"]
        ),
        ModelInfo(
            id: "meta-llama/llama-4-scout-17b-16e-instruct",
            provider: "groq",
            displayName: "Llama 4 Scout 17B 16E Instruct",
            contextWindow: 131_072,
            maxOutput: 8_192,
            supportsTools: true,
            supportsVision: true,
            supportsReasoning: false,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["llama-4-scout", "groq-llama-4-scout"]
        ),
        ModelInfo(
            id: "moonshotai/kimi-k2-instruct",
            provider: "groq",
            displayName: "Kimi K2 Instruct",
            contextWindow: 131_072,
            maxOutput: 16_384,
            supportsTools: true,
            supportsVision: false,
            supportsReasoning: false,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["kimi-k2", "groq-kimi-k2"]
        ),
        ModelInfo(
            id: "llama-3.1-8b-instant",
            provider: "groq",
            displayName: "Llama 3.1 8B Instant",
            contextWindow: 131_072,
            maxOutput: 131_072,
            supportsTools: true,
            supportsVision: false,
            supportsReasoning: false,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["llama-3.1-8b", "groq-llama-3.1-8b"]
        ),
        ModelInfo(
            id: "groq/compound-mini",
            provider: "groq",
            displayName: "Groq Compound Mini",
            contextWindow: 131_072,
            maxOutput: 8_192,
            supportsTools: true,
            supportsVision: false,
            supportsReasoning: false,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["compound-mini", "groq-compound-mini"]
        ),
        ModelInfo(
            id: "allam-2-7b",
            provider: "groq",
            displayName: "Allam 2 7B",
            contextWindow: 4_096,
            maxOutput: 4_096,
            supportsTools: true,
            supportsVision: false,
            supportsReasoning: false,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["allam", "allam-7b"]
        ),
        ModelInfo(
            id: "openai/gpt-oss-safeguard-20b",
            provider: "groq",
            displayName: "GPT-OSS Safeguard 20B",
            contextWindow: 131_072,
            maxOutput: 65_536,
            supportsTools: false,
            supportsVision: false,
            supportsReasoning: true,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["gpt-oss-safeguard", "groq-gpt-oss-safeguard"]
        ),
        ModelInfo(
            id: "meta-llama/llama-guard-4-12b",
            provider: "groq",
            displayName: "Llama Guard 4 12B",
            contextWindow: 131_072,
            maxOutput: 1_024,
            supportsTools: false,
            supportsVision: false,
            supportsReasoning: false,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["llama-guard-4", "groq-llama-guard"]
        ),
        ModelInfo(
            id: "meta-llama/llama-prompt-guard-2-86m",
            provider: "groq",
            displayName: "Llama Prompt Guard 2 86M",
            contextWindow: 512,
            maxOutput: 512,
            supportsTools: false,
            supportsVision: false,
            supportsReasoning: false,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["prompt-guard-86m", "groq-prompt-guard-86m"]
        ),
        ModelInfo(
            id: "meta-llama/llama-prompt-guard-2-22m",
            provider: "groq",
            displayName: "Llama Prompt Guard 2 22M",
            contextWindow: 512,
            maxOutput: 512,
            supportsTools: false,
            supportsVision: false,
            supportsReasoning: false,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["prompt-guard-22m", "groq-prompt-guard-22m"]
        ),
        ModelInfo(
            id: "whisper-large-v3",
            provider: "groq",
            displayName: "Whisper Large V3",
            contextWindow: 448,
            maxOutput: 448,
            supportsTools: false,
            supportsVision: false,
            supportsReasoning: false,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["whisper-v3", "groq-whisper-v3"]
        ),
        ModelInfo(
            id: "whisper-large-v3-turbo",
            provider: "groq",
            displayName: "Whisper Large V3 Turbo",
            contextWindow: 448,
            maxOutput: 448,
            supportsTools: false,
            supportsVision: false,
            supportsReasoning: false,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["whisper-v3-turbo", "groq-whisper-v3-turbo"]
        ),
        ModelInfo(
            id: "canopylabs/orpheus-v1-english",
            provider: "groq",
            displayName: "Orpheus V1 English",
            contextWindow: 4_000,
            maxOutput: 50_000,
            supportsTools: false,
            supportsVision: false,
            supportsReasoning: false,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["orpheus-english", "groq-orpheus-english"]
        ),
        ModelInfo(
            id: "canopylabs/orpheus-arabic-saudi",
            provider: "groq",
            displayName: "Orpheus Arabic Saudi",
            contextWindow: 4_000,
            maxOutput: 50_000,
            supportsTools: false,
            supportsVision: false,
            supportsReasoning: false,
            inputCostPerMillion: nil,
            outputCostPerMillion: nil,
            aliases: ["orpheus-arabic", "groq-orpheus-arabic"]
        ),
    ]
}
