/// Maps SF Symbol system names to Unicode character equivalents for terminal rendering.
public enum SFSymbolMap: Sendable {
    /// Returns a Unicode character for the given SF Symbol name, or nil if no mapping exists.
    public static func unicode(for systemName: String) -> String? {
        mapping[systemName]
    }

    private static let mapping: [String: String] = [
        // Common symbols used in KitchenSink and typical SwiftUI apps
        "checkmark": "✓",
        "checkmark.circle": "✓",
        "checkmark.circle.fill": "✓",
        "xmark": "✕",
        "xmark.circle": "✕",
        "xmark.circle.fill": "✕",
        "plus": "+",
        "plus.circle": "+",
        "minus": "−",
        "minus.circle": "−",
        "gear": "⚙",
        "gearshape": "⚙",
        "star": "★",
        "star.fill": "★",
        "heart": "♥",
        "heart.fill": "♥",
        "trash": "🗑",
        "pencil": "✎",
        "magnifyingglass": "🔍",
        "arrow.left": "←",
        "arrow.right": "→",
        "arrow.up": "↑",
        "arrow.down": "↓",
        "chevron.left": "‹",
        "chevron.right": "›",
        "chevron.up": "ˆ",
        "chevron.down": "ˇ",
        "house": "⌂",
        "house.fill": "⌂",
        "person": "👤",
        "person.fill": "👤",
        "envelope": "✉",
        "envelope.fill": "✉",
        "bell": "🔔",
        "bell.fill": "🔔",
        "lock": "🔒",
        "lock.fill": "🔒",
        "key": "🔑",
        "key.fill": "🔑",
        "terminal": ">_",
        "terminal.fill": ">_",
        "sparkles": "✦",
        "sparkle": "✦",
        "circle": "●",
        "circle.fill": "●",
        "square": "■",
        "square.fill": "■",
        "triangle": "▲",
        "triangle.fill": "▲",
        "doc": "📄",
        "doc.fill": "📄",
        "folder": "📁",
        "folder.fill": "📁",
        "clock": "⏰",
        "clock.fill": "⏰",
        "exclamationmark.triangle": "⚠",
        "exclamationmark.triangle.fill": "⚠",
        "info.circle": "ℹ",
        "info.circle.fill": "ℹ",
        "questionmark.circle": "?",
        "eye": "👁",
        "eye.fill": "👁",
        "eye.slash": "⊘",
        "wifi": "📶",
        "bolt": "⚡",
        "bolt.fill": "⚡",
        "sun.max": "☀",
        "sun.max.fill": "☀",
        "moon": "☾",
        "moon.fill": "☾",
        "cloud": "☁",
        "cloud.fill": "☁",
        "paintbrush": "🖌",
        "paintbrush.fill": "🖌",
        "wrench": "🔧",
        "wrench.fill": "🔧",
        "hammer": "🔨",
        "hammer.fill": "🔨",
        "chart.bar": "📊",
        "chart.bar.fill": "📊",
        "list.bullet": "☰",
        "sidebar.left": "☰",
        "text.alignleft": "☰",
        "play": "▶",
        "play.fill": "▶",
        "pause": "⏸",
        "pause.fill": "⏸",
        "stop": "⏹",
        "stop.fill": "⏹",
        "speaker.wave.2": "🔊",
        "speaker.wave.2.fill": "🔊",
        "photo": "▧",

        // Navigation / browsing symbols
        "globe": "🌐",
        "phone": "📞",
        "phone.fill": "📞",
        "text.bubble": "💬",
        "text.bubble.fill": "💬",
        "music.note": "♪",
        "music.note.list": "♪",
        "magnifyingglass.circle": "🔍",
        "magnifyingglass.circle.fill": "🔍",

        // iGopher / additional symbols
        "bookmark": "◇",
        "bookmark.fill": "◆",
        "book": "☰",
        "link": "🔗",
        "doc.plaintext": "📄",
        "doc.zipper": "📦",
        "film": "🎬",
        "questionmark.app.dashed": "?",
        "display": "🖥",
        "tv": "📺",
        "hand.raised": "✋",
        "hand.raised.fill": "✋",
        "square.and.arrow.up": "↗",
        "ellipsis.circle": "…",
        "ellipsis.circle.fill": "…",
        "calendar": "📅",
    ]
}
